language: r
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email: b.laabs@uni-luebeck.de
    on_success: change
    on_failure: change
